name: Download Wangwen 
on:
  schedule:
    - cron: '7 1,5,10,14,17,22 * * *'
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: '执行下载图片'
        type: boolean
        required: true
        default: true


jobs:
  download-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' # 替换为你要使用的 Python 版本

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Python Script
        run: |
          python wangwen_setup.py # 替换为你的 Python 脚本文件名
      
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: update images data'
          add: './data/wangwen'

      - name: Run Python Script
        run: |
            python wangwen.py # 替换为你的 Python 脚本文件名
  
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
            message: 'chore: update images data'
            add: './images/wangwen'